http://localhost:3001/api/saved

###
POST http://localhost:3001/api/saved
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ja2J3ZG5AZ21haWwuY29tIiwiaWQiOiI2MWI2ZDI2MTBjYzJlY2NjZWY4ZDcyZjYiLCJpYXQiOjE2MzkzNzE0MjEsImV4cCI6MTYzOTM3NTAyMX0.JbL3vEFrmJgJ6pPB2CHLqfdrJhiQmnGAzE0_WxAisi0

{
    "title": "auth working hopeullly",
    "author": "tests",
    "cover": "please",
    "description": "be nice",
    "link": "youtubes",
    "user": "61b187d49c602f5e2b96aa04"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "books": [],
    "email": "nckbwdn@gmail.com",
    "username": "Nick",
    "password": "vicfirth22"
}

###
http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "nckbwdn@gmail.com",
    "password": "vicfirth22"
}