http://localhost:3001/api/saved


###
POST http://localhost:3001/api/saved
Content-Type: application/json

{
    "title": "new",
    "author": "tests",
    "cover": "please",
    "description": "be nice",
    "link": "youtubes",
    "user": "61b187d49c602f5e2b96aa04"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "books": [],
    "username": "testuser",
    "name": "test",
    "password": "test"
}

###
http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "bowdenn"
}